# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Deploy Site to VPS

on:
  push:
    branches: [ "main" ]
    paths:
      - 'quicktrends_files/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SITE_ENV: ${{ secrets.SITE_ENV }}
      VPS_HOST: ${{ secrets.VPS_HOST }}
      VPS_USER: ${{ secrets.VPS_USER }}
      VPS_PASS: ${{ secrets.VPS_PASS }}
    steps:
      - name: Deploy site via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ env.VPS_HOST }}
          username: ${{ env.VPS_USER }}
          password: ${{ env.VPS_PASS }}
          envs: SITE_ENV
          script: |
            set -euo pipefail
            # Ensure code exists/updated on VPS
            REPO_URL="${{ github.server_url }}/${{ github.repository }}.git"
            if [ ! -d /opt/udemybot/.git ]; then
              mkdir -p /opt/udemybot
              git clone --depth=1 "$REPO_URL" /opt/udemybot
            else
              cd /opt/udemybot
              git fetch origin
              git reset --hard origin/main
            fi
            # Sync website files to web root
            mkdir -p /var/www/quicktrends
            # Ensure rsync (if apt-get available)
            if command -v apt-get >/dev/null 2>&1; then
              apt-get update -y
              apt-get install -y rsync
            fi
            if command -v rsync >/dev/null 2>&1; then
              rsync -a --delete /opt/udemybot/quicktrends_files/ /var/www/quicktrends/
            else
              # Fallback: destructive sync via rm + cp
              rm -rf /var/www/quicktrends/*
              cp -a /opt/udemybot/quicktrends_files/. /var/www/quicktrends/
            fi
            # Write site .env from env if provided (multiline safe)
            if [ -n "${SITE_ENV:-}" ]; then
              printf "%s" "${SITE_ENV}" > /var/www/quicktrends/.env
              chown www-data:www-data /var/www/quicktrends/.env
              chmod 600 /var/www/quicktrends/.env
            fi
            chown -R www-data:www-data /var/www/quicktrends
            systemctl reload nginx || true
